apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-analysis
  namespace: canary-analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-analysis
  template:
    metadata:
      labels:
        app: web-analysis
    spec:
      containers:
      - name: web-analysis
        image: web-analysis
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: web-analysis
  namespace: canary-analysis
spec:
  selector:
    app: web-analysis
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: ClusterIP
