server:
  # -- Extra arguments to provide to the Argo server binary.
  ## Ref: https://argo-workflows.readthedocs.io/en/stable/argo-server/#options
  extraArgs:
    - --auth-mode=server
  
  # Argo Workflows server ingress configuration
  ingress:
    # -- Enable an ingress resource for the Argo Workflows server
    enabled: true

    # -- Defines which ingress controller will implement the resource
    ingressClassName: nginx

    # -- Argo Workflows server hostname
    hostname: "argo-workflows.localhost"