apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blue-green-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: blue-green.demo                             # app host address
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rollout-bluegreen-active           # target service name
            port:
              number: 5000