apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docker-config-secret
  namespace: argo-events
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-secret-store
    kind: SecretStore
  target:
    name: docker-config-secret
    creationPolicy: Owner
  data:
  - secretKey: config.json
    remoteRef:
      key: github-creds
      property: DOCKER_CONFIG_JSON